# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5a6d4bf66a7dc57aaeaf8a92835343fb4963e54ee0faa6e20f966fccbbcc5d53cf3f6982e3d328d3cdc206de5cd9bbf24c44497eaf97282698f2dfaafd7d06

test:
  secret_key_base: b6473d14bd89391b25079af5cb4aa57ed5d83dc8f6139c5992a1a6f4864475d6f4331c05808d47430176500d535a9c80b751cad7354cf00a4f151e9febaecc30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
